apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: backstage-postgresql
  data:
  - secretKey: postgres-password
    remoteRef:
      key: kv/rhads-dh
      property: postgresql_password
  - secretKey: password
    remoteRef:
      key: kv/rhads-dh
      property: postgresql_password

